Added new way to call the GATTACA entry script
The user-facing GATTACA script has to be able to change with the new
versions of the docker, to allow the calls to start the docker
appropriate for the various versions.

However, the GATTACA script has (had) two main flaws:
	1- The user had to manually download the proper version of the
	script from the GitHub release page to be sure to use the
	version of the script for their chosen GATTACA version, as the
	latest script (the one that one installs following the README)
	could be *too new* to properly run every container version.
	2- The script had no way to notify the user of a new version of
	the script itself, nor a way to auto-update.

This commit fixes both issues. Now, the GATTACA script merely queries
the docker for the contents of the `cli.sh` file (which is identical to
the old front-facing GATTACA file), and evaluates them. This allows the
user-facing GATTACA script to never change, while changes to the cli are
"version controlled" by the container itself, just like the rest of the
code. So, we get the flexibility and self-update capacity of the docker
container also for the cli script.

The only variable needed by the outside script is the `--version` of
the docker container. For semplicity and security's sake, this was
harcoded to be the first parameter that can be parsed by the script.
The call fails if this requirement is not met.

All old tests pass, with the change of moving the `--version` parameters
at the start of the call, as per above.

It migth not be the best solution, but I'm pretty proud of this one!

diff --git a/GATTACA b/GATTACA
--- a/GATTACA
+++ b/GATTACA
@@ -1,489 +1,35 @@
 #!/usr/bin/env bash
 
-echo # This random echo is to give a bit more space to the help commands.
+version="latest"
 
-function _gattaca_print_general_help {
-    echo "Usage: GATTACA [-h | --help] [-v | --version <version>] [ -l | --log_name <name> ]"
-    echo "       [--verbose] <command> [<args>]"
-    echo
-    echo "Options:"
-    echo "    -v | --version <version>      Specify the version of the docker to run <command> in."
-    echo "    -l | --log_name <name>        Specify the filename of the log, created alongside the"
-    echo "                                  output of many commands."
-    echo "    --verbose                     Passing this flag includes debug information in the"
-    echo "                                  logfiles."
-    echo
-    echo "Available commands:"
-    echo "    init              Create a configuration file for 'GATTACA run'."
-    echo "    run               Perform a differential expression analysis."
-    echo "    prepaffy          Create an expression matrix from Affymetrix .CEL files."
-    echo "    prepagil          Create an expression matrix from Agilent .txt files."
-    echo "    annotate          Annotate an expression file with remote annotations."
-    echo "    versions          Get a list of R packages installed in the docker and their versions."
-    echo "    test              Run the tests associated with the code."
-    echo
-    echo "Use '-h' or '--help' in any subcommand to get additional help and possible options"
-}
+if [ "$1" = "-v" ] || [ "$1" = "--version" ]; then
+    version=$2
+    # No shifts are needed here, the arg is passed also to the evaluated
+    # script, as-is.
 
-
-function _gattaca_help_init {
-    echo "Usage: GATTACA init [-h | --help] <file_path>"
-    echo
-    echo "Create a configuration file for 'GATTACA run' at <file_path>."
-    echo "Note: This command does not produce a log file."
-}
-
-
-function _gattaca_help_run {
-    echo "Usage: GATTACA run [-h | --help] <output_dir> <input_file> <options_file>"
-    echo
-    echo "Perform differential gene analysis on an expression dataset '<input_file>', saving"
-    echo "the output plots and files in '<output_dir>'. The runtime options for this command are"
-    echo "specified in the <options_file>, encoded in yaml. See the 'init' command and the"
-    echo "GATTACA repository README for more information about a specific container version."
-    echo
-    echo "NOTE: The options file will be copied in the same folder as the input file, due"
-    echo "to (self-imposed) limitations in the docker engine."
-}
-
-
-function _gattaca_help_prepaffy {
-    echo "Usage: GATTACA prepaffy [-h | --help] [-r | --remove-controls] [--plot-number <int>]"
-    echo "       [--plot-size <x,y>] [--png] <input_dir> <output_file>"
-    echo
-    echo "Run preprocessing on all .CEL files present in <input_dir> to get a CSV expression matrix,"
-    echo "saved as <output_file>."
-    echo "Diagnostic plots will be saved alongside the output file, in a folder named 'prepaffy Figures'."
-    echo
-    echo "Options:"
-    echo "  -r | --remove-controls      If set, removes control probes from the expression data."
-    echo "  --plot-number <int>         Print only top <int> plots, sorted by distortion score."
-    echo "  --plot-size <x,y>           Plot sizes (in inches) to use for the diagnostic PDF"
-    echo "                              plots. Defaults to '12,5'. Note: Using the '--png'"
-    echo "                              flag produces PNG files at a resolution of 300 ppi."
-    echo "  --png                       Produce PNG files instead of PDF files."
-}
-
-
-function _gattaca_help_annotate {
-    echo "Usage: GATTACA annotate [-h | --help] [-s | --select <selections>] <input_file>"
-    echo "       <output_file> <chip_id>"
-    echo
-    echo "Annotate an expression dataset '<input_file>' with annotations for the chip <chip_id>."
-    echo "Save the output in <output_file>."
-    echo "Read the README for a list of the supported chips for each container version."
-    echo
-    echo "Options:"
-    echo "  -s | --select <selections>         Comma delimited list of selections. Defaults to"
-    echo "                                     'SYMBOL,GENENAME', annotating HUGO symbols and long"
-    echo "                                     gene names."
-}
-
-
-function _gattaca_help_prepagil {
-    echo "Usage: GATTACA prepagil [-h | --help] [-r | --remove-controls] [-p | --grep-pattern <pattern>]"
-    echo "       [--plot-number <int>] [--plot-size <x,y>] [--png] <input_dir> <output_file>"
-    echo
-    echo "This command prepares normalized, log2 transformed expression matrices from Agilent files."
-    echo "Runs on all files in <input_dir> that end in a '.txt' (or <pattern>) to get a CSV expression"
-    echo "matrix, saved as <output_file>."
-    echo "Diagnostic plots will be saved alongside the output file, in a folder named 'prepagil Figures'."
-    echo
-    echo "Options:"
-    echo "  -r | --remove-controls            If set, removes control probes from the expression data."
-    echo "  -p | --grep-pattern <pattern>     The RegEx pattern to match input files with."
-    echo "  --plot-number <int>               Print only top <int> plots, sorted by distortion score."
-    echo "  --plot-size <x,y>                 Plot sizes (in inches) to use for the diagnostic PDF"
-    echo "                                    plots. Defaults to '12,5'. Note: Using the '--png'"
-    echo "                                    flag produces PNG files at a resolution of 300 ppi."
-    echo "  --png                             Produce PNG files instead of PDF files."
-}
-
-
-function _gattaca_assert_is_file {
-    # Assert if a certain path is pointing to a file that exists
-    if test ! -f "$1"; then
-        >&2 echo "Error: '$1' is not a file."
-        exit 1
-    fi
-}
-
-
-function _gattaca_assert_is_directory {
-    # Assert if a certain path is pointing to a directory that exists
-    if test ! -d "$1"; then
-        >&2 echo "Error: '$1' is not a directory."
-        exit 1
-    fi
-}
-
-
-function _gattaca_run_init {
-    target_path="."
-
-    while test $# -gt 0; do
-        case "$1" in
-            -h | --help)
-                _gattaca_help_init
-                exit 0
-            ;;
-            * )
-                break
-            ;;
-        esac
+    # Test that there are no more '-v/--version's around.
+    # The "${@:2:$#}" starts iterating from the 2rd element (to skip the first
+    # -v/--version we already found).
+    for i in "${@:2:$#}"; do
+        if [ "$i" = "-v" ] || [ "$i" = "--version" ]; then
+            echo "ERROR: Version argument ($i) found multiple times."
+            exit 1
+        fi
     done
-
-    if test $# -eq 1; then
-        target_path="$1"
-    elif test $# -eq 0; then
-        >&2 echo "Missing required argument '<file_path>'"
-        exit 1
-    else
-        >&2 echo "Wrong number of arguments: ${#} (expected 1)"
-        exit 1
-    fi
-
-    target_mountpoint="$(dirname "$target_path")"
-    target_name=$(basename -- "$target_path")
-
-    mkdir -p "$target_mountpoint"
-
-    echo "Spooling up docker instance..."
-
-    docker run \
-        --rm \
-        --mount type=bind,source="$target_mountpoint",target=/GATTACA/target \
-        cmalabscience/gattaca:"$version" \
-        "unnamed", "INFO" \
-        "init" "$target_name"
-
-    echo "Created options file in '$target_path'"
-}
-
-function _gattaca_run_run {
-
-    while test $# -gt 0; do
-        case "$1" in
-            -h | --help)
-                _gattaca_help_run
-                exit 0
-            ;;
-            * )
-                break
-            ;;
-        esac
+else
+    # Same as above, but tests it everywhere in the string.
+    for i in "$@"; do
+        if [ "$i" = "-v" ] || [ "$i" = "--version" ]; then
+            echo "ERROR: Version argument ($i) was not the first one passed."
+            exit 1
+        fi
     done
-
-    # <output_dir> <input_file> <options_file>
-    if test $# -eq 3; then
-        target_mountpoint=$(realpath "$1")
-        input_path=$(realpath "$2")
-        options_path=$(realpath "$3")
-    else
-        >&2 echo "Wrong number of arguments: ${#} (expected 3)"
-        exit 1
-    fi
-
-    _gattaca_assert_is_file "$input_path"
-    _gattaca_assert_is_file "$options_path"
-
-    mkdir -p "$target_mountpoint"
-
-    input_filename=$(basename -- "$input_path")
-    input_mountpoint="$(dirname "$input_path")"
-    options_filename=$(basename -- "$options_path")
-    options_mountpoint="$(dirname "$options_path")"
-
-    if [ "${input_filename}" = "${options_filename}" ]; then
-        >&2 echo "Input and option files cannot have the same name. Sorry!"
-        exit 1
-    fi
-
-    if [ ! "$input_mountpoint" = "$options_mountpoint" ]; then
-        echo "Copying options file to input dir..."
-        cp "$options_path" "$input_mountpoint"
-    fi
-
-    echo "Spooling up docker instance..."
-
-    docker run \
-        -it --rm \
-        --mount type=bind,source="$target_mountpoint",target=/GATTACA/target \
-        --mount type=bind,source="$input_mountpoint",target=/GATTACA/input,readonly \
-        cmalabscience/gattaca:"$version" \
-        "$log_name" "$log_level" \
-        "gattaca" "$input_filename" "$options_filename"
-
-    if [ ! "$input_mountpoint" = "$options_mountpoint" ]; then
-        echo "Removing copy of options file from input dir..."
-        rm "$input_mountpoint/$options_filename"
-    fi
-}
-
-function _gattaca_run_prepaffy {
-    remove_controls="FALSE"
-    plot_size="12,5"
-    use_pdf="TRUE"
-    plot_number="Inf"
-
-    while test $# -gt 0; do
-        case "$1" in
-            -h | --help)
-                _gattaca_help_prepaffy
-                exit 0
-            ;;
-            -r | --remove-controls)
-                shift
-                remove_controls="TRUE"
-            ;;
-            --plot-number)
-              shift
-              plot_number="$1"
-              shift
-            ;;
-            --plot-size)
-              shift
-              plot_size=$1
-              shift
-            ;;
-            --png)
-              shift
-              use_pdf="FALSE"
-              ;;
-            * )
-                break
-            ;;
-        esac
-    done
-
-    # <input_dir> <output_file>
-
-    if test $# -eq 2; then
-        input_mountpoint=$(realpath "$1")
-        output_path=$(realpath "$2")
-    else
-        >&2 echo "Wrong number of arguments: ${#} (expected 2)"
-        exit 1
-    fi
-
-    output_mountpoint=$(dirname "$output_path")
-    output_filename=$(basename -- "$output_path")
-
-    mkdir -p "$output_mountpoint"
-
-    _gattaca_assert_is_directory "$input_mountpoint"
-
-    echo "Spooling up docker instance..."
-    docker run \
-        -it --rm \
-        --mount type=bind,source="$output_mountpoint",target=/GATTACA/target \
-        --mount type=bind,source="$input_mountpoint",target=/GATTACA/input,readonly \
-        cmalabscience/gattaca:"$version" \
-        "$log_name" "$log_level" \
-        "prepaffy" "$output_filename" "$remove_controls" "$plot_size" "$use_pdf" "$plot_number"
-}
-
-function _gattaca_run_annotate {
-    selections="SYMBOL,GENENAME"
-
-    while test $# -gt 0; do
-        case "$1" in
-            -h | --help)
-                _gattaca_help_annotate
-                exit 0
-            ;;
-            -s | --select)
-                shift
-                selections="$1"
-                shift
-            ;;
-            * )
-                break
-            ;;
-        esac
-    done
-
-    # <input_file> <output_file> <chip_id>
-
-    if test $# -eq 3; then
-        input_path=$(realpath "$1")
-        target_path="$2"
-        chip_id="$3"
-    else
-        >&2 echo "Wrong number of arguments: ${#} (expected 3)"
-        exit 1
-    fi
-
-    input_mountpoint="$(dirname "$input_path")"
-    target_mountpoint="$(dirname "$target_path")"
-
-    output_filename=$(basename -- "$target_path")
-    input_filename=$(basename -- "$input_path")
-
-    _gattaca_assert_is_file "$input_path"
-
-    mkdir -p "$target_mountpoint"
-
-    echo "Spooling up docker instance..."
-    docker run \
-        -it --rm \
-        --mount type=bind,source="$target_mountpoint",target=/GATTACA/target \
-        --mount type=bind,source="$input_mountpoint",target=/GATTACA/input,readonly \
-        cmalabscience/gattaca:"$version" \
-        "$log_name" "$log_level" \
-        "annotate" "$input_filename" "$output_filename" "$chip_id" "$selections"
-}
-
-function _gattaca_run_prepagil {
-    grep_pattern="*.(txt|TXT)"
-    remove_controls="FALSE"
-    plot_size="12,5"
-    use_pdf="TRUE"
-    plot_number="Inf"
-
-     while test $# -gt 0; do
-        case "$1" in
-            -h | --help)
-                _gattaca_help_prepagil
-                exit 0
-            ;;
-            -r | --remove-controls)
-                shift
-                remove_controls="TRUE"
-            ;;
-            -p | --grep-pattern)
-                shift
-                grep_pattern="$1"
-                shift
-            ;;
-            --plot-number)
-                shift
-                plot_number="$1"
-                shift
-            ;;
-            --plot-size)
-                shift
-                plot_size="$1"
-                shift
-            ;;
-            --png)
-                shift
-                use_pdf="FALSE"
-            ;;
-            * )
-                break
-            ;;
-        esac
-    done
-
-    if test $# -eq 2; then
-        input_dir=$(realpath "$1")
-        target_path="$2"
-    else
-        >&2 echo "Wrong number of arguments: ${#} (expected 2)"
-        exit 1
-    fi
-
-    target_mountpoint="$(dirname "$target_path")"
-    output_filename=$(basename -- "$target_path")
-
-    _gattaca_assert_is_directory "$input_dir"
-
-    mkdir -p "$target_mountpoint"
-
-    echo "Spooling up docker instance..."
-    docker run \
-        -it --rm \
-        --mount type=bind,source="$target_mountpoint",target=/GATTACA/target \
-        --mount type=bind,source="$input_dir",target=/GATTACA/input,readonly \
-        cmalabscience/gattaca:"$version" \
-        "$log_name" "$log_level" \
-        "prepagil" "$output_filename" "$grep_pattern" "$remove_controls" "$plot_size" "$use_pdf" "$plot_number"
-}
-
-function _gattaca_run_tests {
-  docker run \
-      --rm \
-      cmalabscience/gattaca:"$version" \
-      "NULL" "NULL" \
-      "testall"
-}
-
-function _gattaca_run_versions {
-  docker run \
-      --rm \
-      cmalabscience/gattaca:"$version" \
-      "NULL" "NULL" \
-      "versions"
-}
-
-if [ $# == 0 ]; then
-    _gattaca_print_general_help
 fi
 
-version="latest"
-log_level="INFO"
+echo "Running with version '$version'."
 
-while test $# -gt 0; do
-    case "$1" in
-        -h | --help)
-            _gattaca_print_general_help
-            exit 0
-        ;;
-        -v | --version)
-            shift # Get rid of `-v`
-            version="$1"
-            ## TODO: Print out warnings for very old docker images that do
-            # not support some commands.
-            shift
-        ;;
-        -l | --log-name)
-            shift
-            log_name="$1"
-            shift
-        ;;
-        --verbose)
-            shift
-            log_level="DEBUG"
-        ;;
-        init)
-            shift
-            _gattaca_run_init "$@"
-            exit 0
-        ;;
-        run)
-            shift
-            _gattaca_run_run "$@"
-            exit 0
-        ;;
-        prepaffy)
-            shift
-            _gattaca_run_prepaffy "$@"
-            exit 0
-        ;;
-        annotate)
-            shift
-            _gattaca_run_annotate "$@"
-            exit 0
-        ;;
-        prepagil)
-            shift
-            _gattaca_run_prepagil "$@"
-            exit 0
-        ;;
-        test)
-            shift
-            _gattaca_run_tests
-            exit 0
-        ;;
-        versions)
-            shift
-            _gattaca_run_versions
-            exit 0
-        ;;
-        *)
-            echo "Invalid parameter '{$1}'."
-            _gattaca_print_general_help
-            exit 0
-    esac
-done
+# This captures the version-specific script that gives the CLI for GATTACA
+# and runs it as code, so that this script will (almost) never have to be
+# updated by the user.
+GATTACA_CLI="$(docker run --rm cmalabscience/gattaca:"$version" getcli)"
+eval "$GATTACA_CLI"
